### ISSUE TITLE
sql.ErrNoRows error checking

### ISSUE THREAD

**Issue by mickelsonm** [curt-labs/GoAPI#10]
Need to add checks for sql.ErrNoRows( error: sql: no rows in result set) in GET queries. There may be times where it is acceptable to return an empty array versus throwing this error.

"There are lots of places that API calls are bombing out when there is a sql: no rows in result set error. I think this error is very circumstantial. There are places where it's ok if there are no rows in the result set, we shouldn't bomb on that."

**Comment by mickelsonm** [comment]
John says we can close this.

**Comment by stinkyfingers** [comment]
"We can close this."
-John
