### ISSUE TITLE
Brand ID Implementation

### ISSUE THREAD

**Issue by DavidVaini** [curt-labs/GoAPI#16]
In order to integrate other brands such as Aries, into our data, we need to be able to pass a brandID into our calls. This would then get the parts/categories/other data that belongs to just that brandID.

We need to add brandID to multiple tables, the list will be updated below:

In order to integrate other brands such as Aries, into our data, we need to be able to pass a brandID into our calls. This would then get the parts/categories/other data that belongs to just that brandID.

We need to add brandID to multiple tables, the list will be updated below:

* Application Guides
* BlogCategories (1-1)
* ~~BlogPosts~~
* BusinessClass - (1-1)
* Categories (1-1)
* Company (1-M) - one company can subscribe to multiple brands - currently unused
* Contact (1-1)
* ContactType (1-1)
* Customer (1-M) - one customer can subscribe to multiple brands
* FAQ (1-1)
* ~~File - we'll let Chris maintain this on his own via folder separation~~
* ~~FileGallery - again we'll let Chris maintain this, ideally these won't be used as much when we start leverage GCS more~~
* ForumGroup - link to Website [websiteID]
* ~~KioskOrders~~
* LandingPage - link to Website [websiteID]
* Menu - link to Website [websiteID]
* NewsItem (1-M)
* Part (1-1)
* SiteContent - link to Website [websiteID]
* Survey (1-1)
* TechSupport (1-1)
* Testimonial (1-1)
* Tweets (1-1)
* Video (1-1)
* VideoNew (1-M)
* Warehouses (1-M)
* Website (1-M)

Once the tables are updated we need to check all the calls, include where brandID= ? where needed and also include joins wherever needed.

Once we make sure all CURT data is being reported successfully with brandID, we can then get started on migrating over other brands(will be a separate issue).

Separate Issues can be referenced here:
https://github.com/curt-labs/GoAPI/issues/9
https://github.com/curt-labs/v2Mock/issues/58

**Comment by DavidVaini** [comment]
Update: v2Mock BrandID branch has been merged in and published. So far everything looks good, It looks like GoReports, and Cart Integration also needs to be merged in and published as well.  Any others?

**Comment by ninnemana** [comment]
GoSurvey is already implemented

**Comment by DavidVaini** [comment]
CartIntegration is now implemented too:

~~v2Mock -Published and working~~
GoReports - Not published yet (separate branch)
~~GoSurvey - Published~~
~~CartIntegration - Published and working~~
GoAPI - In Progress
~~Dealers -Published and working~~
~~GoAdmin - Published and working~~

So that just leaves GoReports' Brandifier branch to be merged and published and GoAPI.

**Comment by mickelsonm** [comment]
Update: GoReports has been merged and published. This leaves GoAPI and figuring out a good strategy for migrating/merging the current data (between whatever is in CurtDev and in CurtAriesDev databases).
