### ISSUE TITLE
Aries Product Data Migration

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/GoAPI#17]
This is a list of all the tables that need to be migrated from AriesAuto to CurtDev. Some of which have recursive primary key constraints (marked accordingly)

- ~~Categories (parentID restraint)~~
- ~~CatPart~~
- ~~Content~~
- ~~ContentBridge (with foreign key relationships mapped to new Content data)~~
- ~~Part~~
- ~~PartAttribute~~
- ~~PartImages~~
- ~~PartPackage~~
- ~~PartVideo~~
- ~~Price~~
- ~~Testimonial~~
- ~~Video~~
 

All of these could be copied using a series a `insert from select`, maybe I'll write those up and put them in a gist, who knows maybe I'll do it on this nice little Saturday, I don't know, I don't know if we'll have enough time.

**Comment by DavidVaini** [comment]
GoAPI has been converted over to use branding now both in Database statements and redis.

Anything else that needs to be done before we can migrate in Aries Data into CurtDev?

**Comment by stinkyfingers** [comment]
A repo for a Aries->Curt Sql data merge project lives here: https://github.com/aries-auto/sweetData. MJ mentioned that he wasn't sure yet how DATA was going to proceed with application updates, as the path they were going down was messy.

**Comment by DavidVaini** [comment]
The data was merged a while back, somehow this issue was missed. Closing issue
