### ISSUE TITLE
BrandID Database Converted Checklist

### ISSUE THREAD

**Issue by DavidVaini** [curt-labs/GoAPI#20]
I figured I would make a checklist of Controllers that have been converted over to use BrandID:
If you working on one just put your name next to it. These are just DB calls, not redis.
* ~~applicationGuide~~
* ~~blog~~
* ~~brand - doesn't really apply~~
* ~~cart - doesn't really apply~~
* ~~cartIntegration~~
* ~~category - probably will need to be looked at again when working on parts functionality~~
* ~~contact~~
* ~~customer - John Stamos~~
* ~~dealers - John Stamos~~
* ~~faq~~
* ~~forum~~
* ~~geography - doesn't really apply~~
* ~~lifestyle~~
* ~~middleware - doesn't really apply/ done nevertheless~~
* ~~news~~
* ~~part - Need for ARIES~~
* ~~pricing -- part of parts...nothing here now~~
* ~~salesrep  - doesn't really apply~~
* ~~search - doesn't really apply yet...issue of its own really~~
* ~~site.~~
* ~~techSupport - Need for ARIES~~
* ~~testimonials~~
* ~~vehicle - doesn't really apply~~
* ~~videos - Need for ARIES~~
* ~~vinLookup - doesn't really apply~~
* ~~warranty~~
* ~~webProperty - doesn't really apply~~

**Comment by stinkyfingers** [comment]
I see brandID on BusinessClass. I can't fathom why they'd be brand-specific. Can I remove the field from the DB?

**Comment by ninnemana** [comment]
What uses the BusinessClass table?

**Comment by mickelsonm** [comment]
I know on the Aries website, the Where to Buy page uses it...not sure where else though.

**Comment by DavidVaini** [comment]
I thought there was a reason for it, I will have to look into it more. I think the Become A Dealer uses it.

**Comment by DavidVaini** [comment]
If we dont see a reason to keep it, and you remove it from the DB, just make sure to update GoAdmin, and V2Mock, otherwise the queries will break.

**Comment by ninnemana** [comment]
I would just leave it for now.

**Comment by DavidVaini** [comment]
It looks like videos is the only one needed for Aries Initial launch, is that correct?. Now I think Aries was made to work with old part videos since it was made before the new video structure was implemented in GoApi. It can still use the old (any time a video is added in the new goadmin, its also added in the old table too), but eventually I think we should move it over.

**Comment by mickelsonm** [comment]
I think that is correct. However, I don't think Aries calls any of the video endpoints. The only ties to videos is from part videos.

**Comment by stinkyfingers** [comment]
Well, I should have checked. I just pushed videos up, but not partVideos.

**Comment by DavidVaini** [comment]
As we go through these we should also update the redis keys. All you need to do is append the dtx.BrandString to the end of the API Key. 

Example:  
```RedisKey := "Part:All:Brands:" + dtx.BrandString```
The output would be: 
```"Part:All:Brands:1,2"```

**Comment by DavidVaini** [comment]
Looks like CartIntegration and Cart are the only ones that are left for converting over to brandID.

**Comment by ninnemana** [comment]
Cart?

**Comment by DavidVaini** [comment]
oops copied and pasted, that should not need to be updated, correct?

**Comment by mickelsonm** [comment]
If someone else wants to take cart integration, feel free. I am working my way through the customer user controller incorporating the apierror stuff.

**Comment by ninnemana** [comment]
Right, doesn't use branding

**Comment by DavidVaini** [comment]
Cart Integration was finished with this commit:
https://github.com/curt-labs/GoAPI/commit/b8abeb9806ef12077a790ade8ee46e68c421d83b
So as it stands right now, Im gonna close this issue. If individual problems with branding come up they can be resolved with their own issues.
