### ISSUE TITLE
GetPart with incorrect part returns empty part with 199 content objects

### ISSUE THREAD

**Issue by DavidVaini** [curt-labs/GoAPI#23]
If you put in a bogus part like asdf, you get an empty part object with 199 content objects making a very large response that should be either an empty object, or an error response.
http://goapi.curtmfg.com/part/asdfasdf?key=92fe951c-2ca6-11e4-8758-42010af0fd79

**Comment by DavidVaini** [comment]
Issue still exists with bogus int partIDs, like http://goapi.curtmfg.com/part/23?key=92fe951c-2ca6-11e4-8758-42010af0fd79

Sorry @stinkyfingers

**Comment by DavidVaini** [comment]
Scratch that, it works locally, but it failed to publish.

**Comment by stinkyfingers** [comment]
Boomshacka.
