### ISSUE TITLE
branding - contact types

### ISSUE THREAD

**Issue by mickelsonm** [curt-labs/GoAPI#24]
So in the contact types table we have the following entries:

contactTypeID name showOnWebsite brandID
1	General Inquiry	1	1
2	New Customer	1	1
5	COMNET Help	1	1
6	Customer Service	1	1
7	Dealer Locator	1	1
8	Human Resources	1	1
9	Webmaster	1	1
10	Social Media	1	1
11	Tech Services	1	1
12	eCommerce	1	1
13	Advertising & Sponsorships	1	1
14	Shipping	1	1

Right now, all of of these are tied with brandID 1. So the question is...what do we do when we have a brandID of 3? I could picture some of these being shared contact types(ex. General Inquiry, Customer Service, Webmaster, etc), so do we change the database structure to link a type to a group of brands or do we have separate/duplicate entries?

**Comment by DavidVaini** [comment]
Its not like the table would get all that large, honstly I would just have two entries. If we are worried about size we could always throw in a join table with brandID to change the relationship.

**Comment by ninnemana** [comment]
The nature of data in that table being so limited, I have no problem with duplicates.

**Comment by mickelsonm** [comment]
Sounds good. Just wanted a second opinion on it.
