### ISSUE TITLE
Redis Fix

### ISSUE THREAD

**Issue by DavidVaini** [curt-labs/GoAPI#27]
So we decided that we would do a DB call to APIKeyToBrand table to get all the brands for that key.

1.  Every request will take the API Key and specified brandID.
2. If there is a specified brandID, then it doesnt do a database call to check all the brands for that api key.
3. If there is not a specified brandID then it checks the APIKeyToBrand table to see all the brands for that key.
4. In the redis keys, you would append all the brands example:
Parts:All:Brands:1,2,3,4,5
5. If its not cached, the query will pass in the apikey and the specified brand (not set so it would be 0) and the DB would then pull all the parts for with those brandIDs (1,2,3,4,5)

Here is a checklist of the modules for Redis: if you are working on an item, make sure to put your name next to it to minimize the risk of someone else doing the same work you are doing:

* ~~applicationGuide~~
* ~~blog~~
* ~~cartIntegration~~
* ~~category~~
* ~~contact~~
* ~~customer~~
* ~~dealers~~
* ~~faq~~
* ~~forum~~
* ~~lifestyle~~
* ~~news~~
* ~~products~~
* ~~pricing~~
* ~~search~~
* ~~site~~
* ~~techSupport~~
* ~~testimonials~~
* ~~videos~~
* ~~warranty~~
* ~~webProperties~~

**Comment by mickelsonm** [comment]
I am curious to see how well this solution scales/performs. There seems to be a lot of combinations/permutations for brandIDs.

For example, if we have 5 keys linked to various brandIDs/combinations:

	Key A: 1
	Key B: 1,2
	Key C: 1,2,3
	Key D: 1,3
	Key E: 3

Redis keys start looking like:

	<key>:1
	<key>:3
	<key>:1,2
	<key>:1,3
	<key>:1,2,3

You can see where this starts growing and I don't even have all of the combinations listed yet. I know Redis can handle a lot in terms of key-value pairs, but I can already see memory usage increasing.

An idea would be to store it like:
	
	<key>:all
	<key>:1
	<key>:2
	<key>:3

I am not sure on the code yet, but there might be an nice way to group or filter the responses? The simpler we can keep this, the better.

What do you guys think?

**Comment by DavidVaini** [comment]
We talked about this, the problem is the redis response has to hold the same thing as the database call.

Right now if we do a get all parts for a key that has brands 1,2, it returns an array of parts from both brands. Now we need to store this in redis, so we would have to either go into every function and change it to parse out only the responses for that brand, and cache those individual (major code overhaul) or we have to cache them together. If we cache them together, then the key has to specify that. The only good way is to store the brands that go with them. That way if a different key also tries to grab 1,2 atleast that is cached.

I would say most of the time, requests would only have one brand, so in terms of memory usage it wouldnt be that high.

**Comment by DavidVaini** [comment]
I think Alex was right in terms of this would be the best way to implement it right now. Unless we seperate out every response into groups of brands, and then return those, there is no good way to cache them individually, so we are stuck caching them in groups right now, which doing a redis key of "Parts:All:Brands:1,2,3:" would be the appropriate way to index it.

**Comment by DavidVaini** [comment]
I updated the list of "modules" in the original post. I went ahead and crossed out any that were either already done or don't use redis.

**Comment by mickelsonm** [comment]
I just ran a grep command to show me all packages using redis. Here's the list:

	$ grep -r "github.com/curt-labs/GoAPI/helpers/redis" .
	./models/blog/blog_model.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/customer/customer.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/customer/customerDetails.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/customer/location_model.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/customer/price.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/customer/user.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/geography/geo.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/lifestyle/lifestyle.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/news/news_model.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/products/attributes.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/products/category.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/products/content.go:	// "github.com/curt-labs/GoAPI/helpers/redis"
	./models/products/images.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/products/inventory.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/products/make.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/products/packages.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/products/part.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/products/prices.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/products/reviews.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/products/videos.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/products/year.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/site/menu.go:	// "github.com/curt-labs/GoAPI/helpers/redis"
	./models/site/website.go:	// "github.com/curt-labs/GoAPI/helpers/redis"
	./models/vehicle/vehicle.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/video/video.go:	"github.com/curt-labs/GoAPI/helpers/redis"
	./models/webProperty/webProperty_model.go:	"github.com/curt-labs/GoAPI/helpers/redis"

Did we miss anything? I think we may have covered all of them.

**Comment by DavidVaini** [comment]
Looks like all the redis keys have been converted over to list brands, I am gonna close this issue for now.
