### ISSUE TITLE
Vehicle Lookup Brand Specificity 

### ISSUE THREAD

**Issue by DavidVaini** [curt-labs/GoAPI#28]
we need to filter out vehicles that dont have parts associated to them with a specific brand.

For example, Aries might only have 10 vehicles, where CURT might have 10,000. We dont want the lookup for Aries to show all 10000 vehicles.

**Comment by stinkyfingers** [comment]
Fixed with commit f831ee5d5dd61977da1b9f3acd40d3f76bdd7385.
