### ISSUE TITLE
Error Response

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/GoAPI#29]
It would be nice if all `http.Error()` responses used the same type of structure to report back error information. It would be more predictable for someone consuming the API.

Maybe use [apierror](https://github.com/curt-labs/GoAPI/blob/master/helpers/error/error.go)?

**Comment by mickelsonm** [comment]
Just a thought here...that apierror.GenerateError() method should probably be able to handle an xml error response too. Right now it only serializes the error into json.

**Comment by mickelsonm** [comment]
We're getting close to closing this issue....last one is the rest of Customer.

**Comment by mickelsonm** [comment]
The ApiError helper has been fully implemented across the controllers. Let's close this issue now.

**Comment by ninnemana** [comment]
https://github.com/curt-labs/GoAPI/blob/master/controllers/middleware/middleware.go#L53

**Comment by mickelsonm** [comment]
Always one in every crowd :smile:
