### ISSUE TITLE
DataContext Mock - Missing CustomerToBrand

### ISSUE THREAD

**Issue by DavidVaini** [curt-labs/GoAPI#30]
The Mock function for the DataContext does not currently create record(s) in the CustomerToBrand table. This causes some tests to fail because it uses a join in the table to the CustomerToBrand. Without a record in that table, you will get 0 results.

This is what is happening on the Web Property "Get All" Test.

I forsee this being an issue on other tests as well.

**Comment by stinkyfingers** [comment]
I think commit 09dbb2bb00d3f3aec4c58f6f60afe0cb30b40d09 addressed this.

**Comment by ninnemana** [comment]
boom

**Comment by DavidVaini** [comment]
I must have missed that commit, this is what I get for trying to code while being sick :mask: 

Good Job @stinkyfingers
