### ISSUE TITLE
Class property is returning empty

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/GoAPI#31]
http://goapi.curtmfg.com/part/11390?key=9300f7bc-2ca6-11e4-8758-42010af0fd79

https://github.com/curt-labs/GoAPI/blob/master/models/products/part.go#L122

**Comment by DavidVaini** [comment]
issue has been closed with this commit:
https://github.com/curt-labs/GoAPI/commit/08655611d3a514327628f628c9f921010fc4a751
