### ISSUE TITLE
install_sheet is null

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/GoAPI#32]
http://goapi.curtmfg.com/part/11390?key=9300f7bc-2ca6-11e4-8758-42010af0fd79

https://github.com/curt-labs/GoAPI/blob/master/models/products/part.go#L109

**Comment by DavidVaini** [comment]
Issue has been closed with this commit:
https://github.com/curt-labs/GoAPI/commit/ccdb35093664e2d483f3846a107c76d77449a806
