### ISSUE TITLE
/Customer/User endpoint unexpected end of JSON input

### ISSUE THREAD

**Issue by DavidVaini** [curt-labs/GoAPI#33]
GoReports currently isnt allowing anyone to login, The error is being thrown on executing a POST request to the /Customer/User endpoint.

People are unable to login right now because of this.

**Comment by ninnemana** [comment]
`curl -d 'email=*****&password=********' http://goapi.curtmfg.com/customer/auth`, works, what's the difference with how those endpoints are authing?

**Comment by davidvthecoder** [comment]
The response coming back from doing a Post Request for Customer/User is empty.
it is a post request that takes the API Key. I tried with the ***** user, check slack for the api key.

It just makes a post request using the key to login.

**Comment by mickelsonm** [comment]
Here's what the stacktrace looks like:

	[martini] Started POST /customer/user for 172.17.42.1:34353
	[martini] PANIC: Value not found for type *apicontext.DataContext
	/usr/src/go/src/runtime/panic.go:387 (0x425ae8)
		gopanic: reflectcall(unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
	/home/deployer/gosrc/src/github.com/go-martini/martini/router.go:352 (0x4afab1)
		(*routeContext).run: panic(err)
	/home/deployer/gosrc/src/github.com/go-martini/martini/router.go:229 (0x4aeb94)
		(*route).Handle: context.run()
	/home/deployer/gosrc/src/github.com/go-martini/martini/router.go:112 (0x4ad818)
		(*router).Handle: route.Handle(context, res)
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:119 (0x4b06fb)
		Router.Handle.fm: m.Action(r.Handle)
	/usr/src/go/src/runtime/asm_amd64.s:403 (0x44dd35)
		call64: CALLFN(·call64, 64)
	/usr/src/go/src/reflect/value.go:419 (0x6a8805)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/usr/src/go/src/reflect/value.go:296 (0x6a75fc)
		Value.Call: return v.call("Call", in)
	/home/deployer/gosrc/src/github.com/codegangsta/inject/inject.go:102 (0x6b9b57)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:173 (0x4ab9a1)
		(*context).run: _, err := c.Invoke(c.handler())
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:164 (0x4ab8b3)
		(*context).Next: c.run()
	/home/deployer/gosrc/src/github.com/martini-contrib/sessions/sessions.go:95 (0x4ba183)
		func.002: c.Next()
	/usr/src/go/src/runtime/asm_amd64.s:403 (0x44dd35)
		call64: CALLFN(·call64, 64)
	/usr/src/go/src/reflect/value.go:419 (0x6a8805)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/usr/src/go/src/reflect/value.go:296 (0x6a75fc)
		Value.Call: return v.call("Call", in)
	/home/deployer/gosrc/src/github.com/codegangsta/inject/inject.go:102 (0x6b9b57)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:173 (0x4ab9a1)
		(*context).run: _, err := c.Invoke(c.handler())
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:164 (0x4ab8b3)
		(*context).Next: c.run()
	/home/deployer/gosrc/src/github.com/curt-labs/GoAPI/controllers/middleware/middleware.go:60 (0x484a3f)
		func.001: c.Next()
	/usr/src/go/src/runtime/asm_amd64.s:403 (0x44dd35)
		call64: CALLFN(·call64, 64)
	/usr/src/go/src/reflect/value.go:419 (0x6a8805)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/usr/src/go/src/reflect/value.go:296 (0x6a75fc)
		Value.Call: return v.call("Call", in)
	/home/deployer/gosrc/src/github.com/codegangsta/inject/inject.go:102 (0x6b9b57)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:173 (0x4ab9a1)
		(*context).run: _, err := c.Invoke(c.handler())
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:164 (0x4ab8b3)
		(*context).Next: c.run()
	/home/deployer/gosrc/src/github.com/martini-contrib/gzip/gzip.go:37 (0x4b89f8)
		func.001: c.Next()
	/usr/src/go/src/runtime/asm_amd64.s:403 (0x44dd35)
		call64: CALLFN(·call64, 64)
	/usr/src/go/src/reflect/value.go:419 (0x6a8805)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/usr/src/go/src/reflect/value.go:296 (0x6a75fc)
		Value.Call: return v.call("Call", in)
	/home/deployer/gosrc/src/github.com/codegangsta/inject/inject.go:102 (0x6b9b57)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:173 (0x4ab9a1)
		(*context).run: _, err := c.Invoke(c.handler())
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:164 (0x4ab8b3)
		(*context).Next: c.run()
	/home/deployer/gosrc/src/github.com/martini-contrib/gorelic/gorelic.go:15 (0x4b818e)
		Handler: c.Next()
	/usr/src/go/src/runtime/asm_amd64.s:401 (0x44dc55)
		call16: CALLFN(·call16, 16)
	/usr/src/go/src/reflect/value.go:419 (0x6a8805)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/usr/src/go/src/reflect/value.go:296 (0x6a75fc)
		Value.Call: return v.call("Call", in)
	/home/deployer/gosrc/src/github.com/codegangsta/inject/inject.go:102 (0x6b9b57)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:173 (0x4ab9a1)
		(*context).run: _, err := c.Invoke(c.handler())
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:164 (0x4ab8b3)
		(*context).Next: c.run()
	/home/deployer/gosrc/src/github.com/go-martini/martini/recovery.go:142 (0x4b0d39)
		func.004: c.Next()
	/usr/src/go/src/runtime/asm_amd64.s:402 (0x44dcc5)
		call32: CALLFN(·call32, 32)
	/usr/src/go/src/reflect/value.go:419 (0x6a8805)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/usr/src/go/src/reflect/value.go:296 (0x6a75fc)
		Value.Call: return v.call("Call", in)
	/home/deployer/gosrc/src/github.com/codegangsta/inject/inject.go:102 (0x6b9b57)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:173 (0x4ab9a1)
		(*context).run: _, err := c.Invoke(c.handler())
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:164 (0x4ab8b3)
		(*context).Next: c.run()
	/home/deployer/gosrc/src/github.com/go-martini/martini/logger.go:25 (0x4b03ff)
		func.001: c.Next()
	/usr/src/go/src/runtime/asm_amd64.s:403 (0x44dd35)
		call64: CALLFN(·call64, 64)
	/usr/src/go/src/reflect/value.go:419 (0x6a8805)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/usr/src/go/src/reflect/value.go:296 (0x6a75fc)
		Value.Call: return v.call("Call", in)
	/home/deployer/gosrc/src/github.com/codegangsta/inject/inject.go:102 (0x6b9b57)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:173 (0x4ab9a1)
		(*context).run: _, err := c.Invoke(c.handler())
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:69 (0x4aa724)
		(*Martini).ServeHTTP: m.createContext(res, req).run()
	/usr/src/go/src/net/http/server.go:1703 (0x4d745a)
		serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
	/usr/src/go/src/net/http/server.go:1204 (0x4d4f27)
		(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
	/usr/src/go/src/runtime/asm_amd64.s:2232 (0x44fd71)
		goexit:
	[martini] Completed 500 Internal Server Error in 13.567183ms
	2015/01/22 14:44:00 http: multiple response.WriteHeader calls
	[martini] Started POST /customer/user for 172.17.42.1:34360
	2015/01/22 14:44:00 http: multiple response.WriteHeader calls
	[martini] PANIC: Value not found for type *apicontext.DataContext
	/usr/src/go/src/runtime/panic.go:387 (0x425ae8)
		gopanic: reflectcall(unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
	/home/deployer/gosrc/src/github.com/go-martini/martini/router.go:352 (0x4afab1)
		(*routeContext).run: panic(err)
	/home/deployer/gosrc/src/github.com/go-martini/martini/router.go:229 (0x4aeb94)
		(*route).Handle: context.run()
	/home/deployer/gosrc/src/github.com/go-martini/martini/router.go:112 (0x4ad818)
		(*router).Handle: route.Handle(context, res)
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:119 (0x4b06fb)
		Router.Handle.fm: m.Action(r.Handle)
	/usr/src/go/src/runtime/asm_amd64.s:403 (0x44dd35)
		call64: CALLFN(·call64, 64)
	/usr/src/go/src/reflect/value.go:419 (0x6a8805)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/usr/src/go/src/reflect/value.go:296 (0x6a75fc)
		Value.Call: return v.call("Call", in)
	/home/deployer/gosrc/src/github.com/codegangsta/inject/inject.go:102 (0x6b9b57)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:173 (0x4ab9a1)
		(*context).run: _, err := c.Invoke(c.handler())
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:164 (0x4ab8b3)
		(*context).Next: c.run()
	/home/deployer/gosrc/src/github.com/martini-contrib/sessions/sessions.go:95 (0x4ba183)
		func.002: c.Next()
	/usr/src/go/src/runtime/asm_amd64.s:403 (0x44dd35)
		call64: CALLFN(·call64, 64)
	/usr/src/go/src/reflect/value.go:419 (0x6a8805)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/usr/src/go/src/reflect/value.go:296 (0x6a75fc)
		Value.Call: return v.call("Call", in)
	/home/deployer/gosrc/src/github.com/codegangsta/inject/inject.go:102 (0x6b9b57)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:173 (0x4ab9a1)
		(*context).run: _, err := c.Invoke(c.handler())
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:164 (0x4ab8b3)
		(*context).Next: c.run()
	/home/deployer/gosrc/src/github.com/curt-labs/GoAPI/controllers/middleware/middleware.go:60 (0x484a3f)
		func.001: c.Next()
	/usr/src/go/src/runtime/asm_amd64.s:403 (0x44dd35)
		call64: CALLFN(·call64, 64)
	/usr/src/go/src/reflect/value.go:419 (0x6a8805)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/usr/src/go/src/reflect/value.go:296 (0x6a75fc)
		Value.Call: return v.call("Call", in)
	/home/deployer/gosrc/src/github.com/codegangsta/inject/inject.go:102 (0x6b9b57)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:173 (0x4ab9a1)
		(*context).run: _, err := c.Invoke(c.handler())
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:164 (0x4ab8b3)
		(*context).Next: c.run()
	/home/deployer/gosrc/src/github.com/martini-contrib/gzip/gzip.go:37 (0x4b89f8)
		func.001: c.Next()
	/usr/src/go/src/runtime/asm_amd64.s:403 (0x44dd35)
		call64: CALLFN(·call64, 64)
	/usr/src/go/src/reflect/value.go:419 (0x6a8805)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/usr/src/go/src/reflect/value.go:296 (0x6a75fc)
		Value.Call: return v.call("Call", in)
	/home/deployer/gosrc/src/github.com/codegangsta/inject/inject.go:102 (0x6b9b57)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:173 (0x4ab9a1)
		(*context).run: _, err := c.Invoke(c.handler())
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:164 (0x4ab8b3)
		(*context).Next: c.run()
	/home/deployer/gosrc/src/github.com/martini-contrib/gorelic/gorelic.go:15 (0x4b818e)
		Handler: c.Next()
	/usr/src/go/src/runtime/asm_amd64.s:401 (0x44dc55)
		call16: CALLFN(·call16, 16)
	/usr/src/go/src/reflect/value.go:419 (0x6a8805)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/usr/src/go/src/reflect/value.go:296 (0x6a75fc)
		Value.Call: return v.call("Call", in)
	/home/deployer/gosrc/src/github.com/codegangsta/inject/inject.go:102 (0x6b9b57)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:173 (0x4ab9a1)
		(*context).run: _, err := c.Invoke(c.handler())
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:164 (0x4ab8b3)
		(*context).Next: c.run()
	/home/deployer/gosrc/src/github.com/go-martini/martini/recovery.go:142 (0x4b0d39)
		func.004: c.Next()
	/usr/src/go/src/runtime/asm_amd64.s:402 (0x44dcc5)
		call32: CALLFN(·call32, 32)
	/usr/src/go/src/reflect/value.go:419 (0x6a8805)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/usr/src/go/src/reflect/value.go:296 (0x6a75fc)
		Value.Call: return v.call("Call", in)
	/home/deployer/gosrc/src/github.com/codegangsta/inject/inject.go:102 (0x6b9b57)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:173 (0x4ab9a1)
		(*context).run: _, err := c.Invoke(c.handler())
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:164 (0x4ab8b3)
		(*context).Next: c.run()
	/home/deployer/gosrc/src/github.com/go-martini/martini/logger.go:25 (0x4b03ff)
		func.001: c.Next()
	/usr/src/go/src/runtime/asm_amd64.s:403 (0x44dd35)
		call64: CALLFN(·call64, 64)
	/usr/src/go/src/reflect/value.go:419 (0x6a8805)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/usr/src/go/src/reflect/value.go:296 (0x6a75fc)
		Value.Call: return v.call("Call", in)
	/home/deployer/gosrc/src/github.com/codegangsta/inject/inject.go:102 (0x6b9b57)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:173 (0x4ab9a1)
		(*context).run: _, err := c.Invoke(c.handler())
	/home/deployer/gosrc/src/github.com/go-martini/martini/martini.go:69 (0x4aa724)
		(*Martini).ServeHTTP: m.createContext(res, req).run()
	/usr/src/go/src/net/http/server.go:1703 (0x4d745a)
		serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
	/usr/src/go/src/net/http/server.go:1204 (0x4d4f27)
		(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
	/usr/src/go/src/runtime/asm_amd64.s:2232 (0x44fd71)
		goexit:
	[martini] Completed 500 Internal Server Error in 10.558424ms

**Comment by stinkyfingers** [comment]
Failed because /customer/user is an excused route. Should it be? Kinda doesn't seem like it.

**Comment by DavidVaini** [comment]
It should be an excused route, because its an authentication key. Essentially we dont want the middleware to handle that key, otherwise it would fail the api key check and result in a 401 before it even gets to the controller. In this case this controller is actually authenticating it rather than the middleware.

**Comment by DavidVaini** [comment]
fixed with this commit: 
https://github.com/curt-labs/GoAPI/commit/439f8c76bd64c434098c6b6946ed725bdaeffe87
