### ISSUE TITLE
Pricing Not Flowing Properly

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/GoAPI#35]
http://ariesautoapi.curtmfg.com/part/old/1043?key=883d4046-8b96-11e4-9475-42010af00d4e

**Comment by ninnemana** [comment]
Ok not an import bug...sometimes I get a full pricing object, sometimes a halfway object, sometimes null.

**Comment by DavidVaini** [comment]
https://i.imgflip.com/hiund.jpg

**Comment by stinkyfingers** [comment]
This part's data is in the DB this way. I have unomitemptied the price field.

83021	2060031	Jobber	385.00	0	2015-02-06 05:53:41
83022	2060031	List	0.00	0	2015-02-06 05:53:41

**Comment by mickelsonm** [comment]
To go along with what John said here....if you run this query:

```sql
select p.oldPartNumber, pr.partID, pr.priceType, pr.price, pr.enforced, pr.dateModified 
from Price pr
join Part p on p.partID = pr.partID
where pr.price = 0
```

It looks like there may have been an issue with the data migration process? There's over 4400 prices that   are at $0.00....

**Comment by ninnemana** [comment]
I'm gonna close this and mark it as a data issue.
