### ISSUE TITLE
Invalid Part Response

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/GoAPI#39]
I'd image we want `http://goapi.curtmfg.com/part/1100012345?key=9300f7bc-2ca6-11e4-8758-42010af0fd79` to respond with the ApiError{}, not an empty part object.

**Comment by ninnemana** [comment]
Part `1100012345` doesn't exist btw.

**Comment by DavidVaini** [comment]
fixed with this commit:

https://github.com/curt-labs/GoAPI/commit/f0f33d9bc58879220d4d15d4966bf5776723b6cd
