### ISSUE TITLE
broken scans?

### ISSUE THREAD

**Issue by mickelsonm** [curt-labs/GoAPI#40]
API went down, but here's some stacktraces:

	goroutine 51649 [runnable]:
	net.(*pollDesc).Wait(0xc20a5e1f00, 0x72, 0x0, 0x0)
		/usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
	net.(*pollDesc).WaitRead(0xc20a5e1f00, 0x0, 0x0)
		/usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
	net.(*netFD).Read(0xc20a5e1ea0, 0xc20ab70000, 0x1000, 0x1000, 0x0, 0x7f23c99ebd30, 0xc20ab48f08)
		/usr/src/go/src/net/fd_unix.go:242 +0x40f
	net.(*conn).Read(0xc20ab22298, 0xc20ab70000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/usr/src/go/src/net/net.go:121 +0xdc
	github.com/go-sql-driver/mysql.(*buffer).fill(0xc20a6e7600, 0x4, 0x0, 0x0)
		/home/deployer/gosrc/src/github.com/go-sql-driver/mysql/buffer.go:57 +0x2aa
	github.com/go-sql-driver/mysql.(*buffer).readNext(0xc20a6e7600, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
		/home/deployer/gosrc/src/github.com/go-sql-driver/mysql/buffer.go:86 +0x68
	github.com/go-sql-driver/mysql.(*mysqlConn).readPacket(0xc20a6e7600, 0x0, 0x0, 0x0, 0x0, 0x0)
		/home/deployer/gosrc/src/github.com/go-sql-driver/mysql/packets.go:30 +0xa1
	github.com/go-sql-driver/mysql.(*mysqlConn).readInitPacket(0xc20a6e7600, 0x0, 0x0, 0x0, 0x0, 0x0)
		/home/deployer/gosrc/src/github.com/go-sql-driver/mysql/packets.go:131 +0x72
	github.com/go-sql-driver/mysql.MySQLDriver.Open(0xc20aaac300, 0x5f, 0x0, 0x0, 0x0, 0x0)
		/home/deployer/gosrc/src/github.com/go-sql-driver/mysql/driver.go:85 +0x4c9
	github.com/go-sql-driver/mysql.(*MySQLDriver).Open(0xf1ce60, 0xc20aaac300, 0x5f, 0x0, 0x0, 0x0, 0x0)
		<autogenerated>:6 +0xcf
	database/sql.(*DB).conn(0xc20a46a280, 0x4453ce, 0x0, 0x0)
		/usr/src/go/src/database/sql/sql.go:664 +0x506
	database/sql.(*DB).prepare(0xc20a46a280, 0xd13fb0, 0x1df, 0x42323a, 0x0, 0x0)
		/usr/src/go/src/database/sql/sql.go:848 +0x4b
	database/sql.(*DB).Prepare(0xc20a46a280, 0xd13fb0, 0x1df, 0x5f, 0x0, 0x0)
		/usr/src/go/src/database/sql/sql.go:833 +0x79
	github.com/curt-labs/GoAPI/models/customer/content.GetPartContent(0x1fbd46, 0xc2082dbdd2, 0x24, 0xf1ce60, 0x0, 0x0, 0x0, 0x0)
		/home/deployer/gosrc/src/github.com/curt-labs/GoAPI/models/customer/content/part.go:129 +0x1a9
	github.com/curt-labs/GoAPI/models/products.func·024()
		/home/deployer/gosrc/src/github.com/curt-labs/GoAPI/models/products/part.go:679 +0x73
	created by github.com/curt-labs/GoAPI/models/products.(*Part).BindCustomer
		/home/deployer/gosrc/src/github.com/curt-labs/GoAPI/models/products/part.go:693 +0x3cb

	goroutine 51558 [chan receive]:
	database/sql.(*DB).connectionOpener(0xc20a6ace60)
		/usr/src/go/src/database/sql/sql.go:589 +0x4c
	created by database/sql.Open
		/usr/src/go/src/database/sql/sql.go:452 +0x31c

	goroutine 51527 [chan send]:
	github.com/curt-labs/GoAPI/models/products.func·012()
		/home/deployer/gosrc/src/github.com/curt-labs/GoAPI/models/products/part.go:246 +0x1b3
	created by github.com/curt-labs/GoAPI/models/products.(*Part).FromDatabase
		/home/deployer/gosrc/src/github.com/curt-labs/GoAPI/models/products/part.go:247 +0xb28

	goroutine 51635 [chan receive]:
	database/sql.(*DB).connectionOpener(0xc20aad9540)
		/usr/src/go/src/database/sql/sql.go:589 +0x4c
	created by database/sql.Open
		/usr/src/go/src/database/sql/sql.go:452 +0x31c

	goroutine 51642 [runnable]:
	net.(*pollDesc).Wait(0xc20a5e1bf0, 0x72, 0x0, 0x0)
		/usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
	net.(*pollDesc).WaitRead(0xc20a5e1bf0, 0x0, 0x0)
		/usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
	net.(*netFD).Read(0xc20a5e1b90, 0xc20ab5c000, 0x1000, 0x1000, 0x0, 0x7f23c99ebd30, 0xc20ab49ab8)
		/usr/src/go/src/net/fd_unix.go:242 +0x40f
	net.(*conn).Read(0xc20ab22248, 0xc20ab5c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/usr/src/go/src/net/net.go:121 +0xdc
	bufio.(*Reader).fill(0xc20aaad0e0)
		/usr/src/go/src/bufio/bufio.go:97 +0x1ce
	bufio.(*Reader).ReadSlice(0xc20aaad0e0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
		/usr/src/go/src/bufio/bufio.go:295 +0x257
	github.com/garyburd/redigo/redis.(*conn).readLine(0xc20a46abe0, 0x0, 0x0, 0x0, 0x0, 0x0)
		/home/deployer/gosrc/src/github.com/garyburd/redigo/redis/conn.go:228 +0x6d
	github.com/garyburd/redigo/redis.(*conn).readReply(0xc20a46abe0, 0x0, 0x0, 0x0, 0x0)
		/home/deployer/gosrc/src/github.com/garyburd/redigo/redis/conn.go:301 +0x66
	github.com/garyburd/redigo/redis.(*conn).Do(0xc20a46abe0, 0xb68a10, 0x5, 0xc20ab57680, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0)
		/home/deployer/gosrc/src/github.com/garyburd/redigo/redis/conn.go:447 +0x5c6
	github.com/garyburd/redigo/redis.(*pooledConnection).Do(0xc20ab66900, 0xb68a10, 0x5, 0xc20ab57680, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0)
		/home/deployer/gosrc/src/github.com/garyburd/redigo/redis/pool.go:365 +0xf0
	github.com/curt-labs/GoAPI/helpers/redis.Setex(0xc20818ad50, 0x22, 0xb0a060, 0x0, 0x15180, 0x0, 0x0)
		/home/deployer/gosrc/src/github.com/curt-labs/GoAPI/helpers/redis/redis.go:86 +0x66a
	created by github.com/curt-labs/GoAPI/models/products.(*Part).GetContent
		/home/deployer/gosrc/src/github.com/curt-labs/GoAPI/models/products/part.go:655 +0xcc1

	goroutine 51526 [runnable]:
	net.(*pollDesc).Wait(0xc209a65330, 0x72, 0x0, 0x0)
		/usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
	net.(*pollDesc).WaitRead(0xc209a65330, 0x0, 0x0)
		/usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
	net.(*netFD).Read(0xc209a652d0, 0xc20aa0d000, 0x1000, 0x1000, 0x0, 0x7f23c99ebd30, 0xc20aaa7d80)
		/usr/src/go/src/net/fd_unix.go:242 +0x40f
	net.(*conn).Read(0xc209baf2d8, 0xc20aa0d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/usr/src/go/src/net/net.go:121 +0xdc
	github.com/go-sql-driver/mysql.(*buffer).fill(0xc20a40fe80, 0x4, 0x0, 0x0)
		/home/deployer/gosrc/src/github.com/go-sql-driver/mysql/buffer.go:57 +0x2aa
	github.com/go-sql-driver/mysql.(*buffer).readNext(0xc20a40fe80, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
		/home/deployer/gosrc/src/github.com/go-sql-driver/mysql/buffer.go:86 +0x68
	github.com/go-sql-driver/mysql.(*mysqlConn).readPacket(0xc20a40fe80, 0x0, 0x0, 0x0, 0x0, 0x0)
		/home/deployer/gosrc/src/github.com/go-sql-driver/mysql/packets.go:30 +0xa1
	github.com/go-sql-driver/mysql.(*mysqlConn).readResultSetHeaderPacket(0xc20a40fe80, 0xc20aaa7d70, 0x0, 0x0)
		/home/deployer/gosrc/src/github.com/go-sql-driver/mysql/packets.go:421 +0x40
	github.com/go-sql-driver/mysql.(*mysqlStmt).Query(0xc20aa77ec0, 0xc20aaa7d70, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
		/home/deployer/gosrc/src/github.com/go-sql-driver/mysql/statement.go:91 +0x20f
	database/sql.rowsiFromStatement(0x7f23c99f7d18, 0xc20aa79260, 0x7f23c99f7cb0, 0xc20aa77ec0, 0xc20a763b18, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
		/usr/src/go/src/database/sql/sql.go:1489 +0x3a4
	database/sql.(*Stmt).Query(0xc20aab4200, 0xc20a763b18, 0x1, 0x1, 0x0, 0x0, 0x0)
		/usr/src/go/src/database/sql/sql.go:1446 +0x312
	database/sql.(*Stmt).QueryRow(0xc20aab4200, 0xc20a763b18, 0x1, 0x1, 0x0)
		/usr/src/go/src/database/sql/sql.go:1509 +0x46
	github.com/curt-labs/GoAPI/models/products.(*Part).PartBreadcrumbs(0xc20895fd40, 0xc208f0a8c0, 0x0, 0x0)
		/home/deployer/gosrc/src/github.com/curt-labs/GoAPI/models/products/part.go:787 +0x6c4
	github.com/curt-labs/GoAPI/models/products.func·011()
		/home/deployer/gosrc/src/github.com/curt-labs/GoAPI/models/products/part.go:234 +0x50
	created by github.com/curt-labs/GoAPI/models/products.(*Part).FromDatabase
		/home/deployer/gosrc/src/github.com/curt-labs/GoAPI/models/products/part.go:239 +0xa3f

**Comment by DavidVaini** [comment]
Do you know which endpoint was trying to be hit on this, looks like something part related.

**Comment by mickelsonm** [comment]
Not specifically...might not even be an issue anymore. However, it probably wouldn't hurt to check out the mentioned line numbers/associated code and follow it to see if there might be some nullable parameters that aren't properly handled...

**Comment by DavidVaini** [comment]
There was a scan issue with a null text property in Get Content, fixed with this commit:
https://github.com/curt-labs/GoAPI/commit/f4628796a700857fb0fb82fe066e2e9e4255e165
