### ISSUE TITLE
Inconsistent Part Response

### ISSUE THREAD

**Issue by DavidVaini** [curt-labs/GoAPI#41]
http://goapi.curtmfg.com/part/11000?key=5e0b0b0c-bb97-11e4-8323-da3578bd4b40

If you keep refreshing the page the response changes.

**Comment by ninnemana** [comment]
Yeah, I've noticed that also. Like part #11000 should have pricing, categories, and videos, I'm seeing null for all three.

Sure at this point it's probably cached that way, but it never should have been cached as null.

**Comment by DavidVaini** [comment]
well its strange because if you keep refreshing even after it changes it changes again.

**Comment by DavidVaini** [comment]
The issue is also on the GetOldPartNumber, it can be seen here:
http://ariesautoapi.curtmfg.com/part/old/CH01611501?key=883d4046-8b96-11e4-9475-42010af00d4e

Huge difference in response.

**Comment by ninnemana** [comment]
Oh yeah very different. It does seem to have some consistency to how it's failing though. When it's missing stuff, it always seems to be the same properties that are missing.

**Comment by DavidVaini** [comment]
yep, looking at redis, reviews, packages, install sheet, related, videos, images are null

davidvaini [9:55 AM]
so sometimes its pulling from redis and sometimes its not

**Comment by DavidVaini** [comment]
Issue was fixed with this commit:
https://github.com/curt-labs/GoAPI/commit/8f0120b8966553510f3ff29aa6e04d2ec63e01d8

There is a seperate side issue causing similar behavior when a user's api key is not tied to any brands.

**Comment by ninnemana** [comment]
There are still quite a few instances where you can make a lookup request, get parts with all properties (attributes,videos,content, etc.) populated, then make the same request a second time, and some of those properties will be `null`.

I've checked redis for the values after the properties start responding `null`, and they're stored in redis as `nil` also. IMO it shouldn't be getting pushed to redis if it's `nil`.

**Comment by DavidVaini** [comment]
Okay so after sorting the vehicles response on the part object, I noticed the response kept coming back the same. I have tried category parts calls, vehicle lookups, and individual part calls, All seem consistent now.  Anyone know of a call that is still inconsistent?

**Comment by DavidVaini** [comment]
So I just tried a bunch more API calls. I am still getting consistent responses, so I will close this for now. If you find any inconsistencies please reopen.
