### ISSUE TITLE
Contact Submission

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/GoAPI#42]
https://github.com/curt-labs/GoAPI/blob/ab7eefeb50b81f0d33800497fd155b3b71e7bf45/controllers/contact/contact.go#L59

This should be changed to be less specific to becoming a dealer. We know the contact type that they are submitting to, so we could use that information to be more specific.

Also, let's add a brand specification to the information sent in the email.

**Comment by DavidVaini** [comment]
added with this commit:
https://github.com/curt-labs/GoAPI/commit/d60ae57ddcff3810d1e5a4c90e7de3016f648953
