### ISSUE TITLE
SSL Update

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/GoAPI#44]
Currently the SSL cert is an SHA1 certificate, we should probably update to SHA2 so Google doesn't get mad at us.

https://www.ssllabs.com/ssltest/analyze.html?d=curtmfg.com

**Comment by DavidVaini** [comment]
This might seem like a silly question, but where is our SSL cert stored right now? I don't think I have ever messed with it in the past.

**Comment by ninnemana** [comment]
I'll have to download a new one from GoDaddy, I've been meaning to talk to @pmcginley about getting it.....forgot which account it's on.

The current certificates are stored on each app server, but those are just SHA1.

**Comment by DavidVaini** [comment]
IT is currently showing up as SHA256withRSA, but still a F grade because of ssl2, do we want to close this issue or keep it open?
