### ISSUE TITLE
Aggregate All Part Numbers

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/GoAPI#46]
We need to figure out the best way to implement getting a list of all the part numbers that are query-able. Not sure the best way to implement this with performance in mind; array of part numbers, array of part objects, array of basic part data (part num, status, date added, date modified, etc).

**Comment by DavidVaini** [comment]
By query-able, do you mean status 800,900?

GetAllPartID's is a large single call to make, but on the other hand, if you do a GetAllPartID's you are probably using that to loop through and make a bunch of calls on each of those partID's.

So I guess do you want a bunch of smaller calls, or just a single query that grabs all base parts?

**Comment by ninnemana** [comment]
You won't be able to return a full part object for all of the parts in the system, it will get timed out. I think we return an array of part nums or an array of basic part (part num, status, date added, date modified, etc) objects, we'll still have the series of small requests to follow.

Most of the part objects on the small requests will be getting pulled directly from Redis anyhow.

**Comment by DavidVaini** [comment]
Alright, ill return an array of basic parts. Do we want to include UPC on this? if so it means that parts without UPC wont be returned.
```sql
select * from Part as p
left join PartAttribute as pa on pa.partID = p.partID
where (p.status = 800 || p.status = 900) && pa.field = "upc"
```

**Comment by ninnemana** [comment]
Sure

**Comment by DavidVaini** [comment]
The new endpoint is here:
http://goapi.curtmfg.com/part/all?key=

takes about 500ms to load, not too shabby.

**Comment by DavidVaini** [comment]
oh and it was closed with this commit:
https://github.com/curt-labs/GoAPI/commit/ba743f8e426109e0563b781eb0ed001a9a293996
