### ISSUE TITLE
MongoDB Use Case

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/GoAPI#49]
We've learned some things from using NoSQL lately that could be greatly beneficial to speeding up some latency issues in GoAPI. I'm wondering if we want to experiment with a fan out process and incorporate a NoSQL layer into the API.

We could continue routing updates in the Admin tool to MySQL and utilize the fan-out process that is currently in place for populating elastic search, redis, etc. We would just need to an a process for pushing parts and other data into a NoSQL cluster.

This isn't a need for going live, but we may end up in a situation where we'll need it to feel comfortable and confident with a strong throughput to do some of things we'd like to with GoAPI.

**Comment by DavidVaini** [comment]
I agree with this, It would be nice to roll out certain endpoints at a time. For pushing the parts into NoSQL, What kind of process and where would the process be located?

**Comment by mickelsonm** [comment]
This line right here is what sold David: "...we'll need it to feel comfortable and confident with a strong throughput to do some of things we'd like to with GoAPI".... Comfortable, confident, strong throughput...you had him at that...

**Comment by ninnemana** [comment]
Started implementing here: https://github.com/curt-labs/GoAPI/tree/mongo

**Comment by ninnemana** [comment]
That's a pretty impressive difference. Mongo responds twice as fast and seem to be much more stable around it's fastest point, whereas MySQL had the random 2.5+- requests. I'm sure if this is done against the categories there would be an even larger difference.... and less panic errors.

==

#### MongoDB

→ boom -n 1000 -c 10 http://146.148.75.97/part/1042\?key\=9300f7bc-2ca6-11e4-8758-42010af0fd79
1000 / 1000 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 %

Summary:
  Total:	24.2891 secs.
  Slowest:	0.7000 secs.
  Fastest:	0.1467 secs.
  Average:	0.2421 secs.
  Requests/sec:	41.1707

Status code distribution:
  [200]	1000 responses

Response time histogram:
  0.147 [1]	|
  0.202 [320]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.257 [378]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.313 [158]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.368 [84]	|∎∎∎∎∎∎∎∎
  0.423 [39]	|∎∎∎∎
  0.479 [14]	|∎
  0.534 [3]	|
  0.589 [0]	|
  0.645 [0]	|
  0.700 [3]	|

Latency distribution:
  10% in 0.1770 secs.
  25% in 0.1958 secs.
  50% in 0.2225 secs.
  75% in 0.2706 secs.
  90% in 0.3400 secs.
  95% in 0.3782 secs.
  99% in 0.4554 secs.

----

#### MySQL

→ boom -n 1000 -c 10 http://goapi.curtmfg.com/part/old/1042\?key\=9300f7bc-2ca6-11e4-8758-42010af0fd79
1000 / 1000 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 %

Summary:
  Total:	50.3509 secs.
  Slowest:	2.3875 secs.
  Fastest:	0.2251 secs.
  Average:	0.5020 secs.
  Requests/sec:	19.8606

Status code distribution:
  [200]	1000 responses

Response time histogram:
  0.225 [1]	|
  0.441 [506]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.658 [442]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.874 [14]	|∎
  1.090 [1]	|
  1.306 [1]	|
  1.523 [0]	|
  1.739 [1]	|
  1.955 [16]	|∎
  2.171 [16]	|∎
  2.387 [2]	|

Latency distribution:
  10% in 0.3471 secs.
  25% in 0.3899 secs.
  50% in 0.4401 secs.
  75% in 0.5094 secs.
  90% in 0.5860 secs.
  95% in 0.6716 secs.
  99% in 2.0740 secs.

**Comment by DavidVaini** [comment]
Mongo branch has been merged in. Both Parts and Categories have been fanned out.
