### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/GoAPI#5]
https fails with error: Get https://goapi.curtmfg.com/category?key=8aee0620-412e-47fc-900a-947820ea1c1d: x509: certificate signed by unknown authority.

We need to fix the SSL in nginx and haproxy

**Comment by DavidVaini** [comment]
I believe this was fixed a while back, now if I hit an endpoint with https I get a response.

**Comment by ninnemana** [comment]
Yeah I don't remember what I did to make it throw that error, but I can't reproduce anymore.

I know https is failing for the aries API, but I'm sure it's completely missing the certificate.
