### ISSUE TITLE
Update Vehicle Documentation

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/GoAPI#50]
The documentation for implementing the `/vehicle` lookup is still referencing a smart URL pattern using the old `GET` style endpoints. This needs to be updated to reflect the new `POST` request using the `JSON` object and/or form data.

**Comment by DavidVaini** [comment]
Somewhat Related Issue:
https://github.com/curt-labs/GoAPI/issues/47

**Comment by ninnemana** [comment]
Are you sure?

**Comment by DavidVaini** [comment]
About it being somewhat related to GoAPI Documentation?

I mean this page could be updated:
https://github.com/curt-labs/GoAPI/blob/master/docs/Vehicle.md

But if we are going to automate documentation then wouldnt that close both of these issues?

**Comment by ninnemana** [comment]
haha no the assignment, just giving you a hard time.

**Comment by DavidVaini** [comment]
haha okay, yeah if he needs any help he can ask me, it will be good for him to learn more about the API. And If it proves to be a little bit much, I can always take over, but I am sure @TopShelfBullard 's got this.

**Comment by ninnemana** [comment]
In the long term the automated documentation is the way to go, but we should have false documentation up until that point, if we're going to have a document, might as well make it correct.

**Comment by DavidVaini** [comment]
Yeah I guess you are right, I think I am going to do this one real quick, shouldn't take but a few minutes. He can still work on the automated documentation.

**Comment by ninnemana** [comment]
Of course I am David.

**Comment by DavidVaini** [comment]
Closed with this commit:
https://github.com/curt-labs/GoAPI/commit/da6103b8105b9aad07242601e25a792a87ab8fbb
