### ISSUE TITLE
MySQL Deadlock?

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/GoAPI#53]
I think this call is creating a deadlock in the MySQL connection.

http://goapi.curtmfg.com/category/3/parts?count=10&key=[kley]&page=1

**Comment by stinkyfingers** [comment]
Possibly, I can replicate the problem with this call locally:  http://localhost:8080/category/3. The 4th try usually kills GoAPI.

**Comment by ninnemana** [comment]
Hopefully https://github.com/curt-labs/GoAPI/tree/mongo will take care of this.

**Comment by DavidVaini** [comment]
no longer an issue as mongo has been  merged in.
