### ISSUE TITLE
F-450 Not Aggregating in Luverne Lookup

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/GoAPI#75]
There are products that are tagged for a 2017 Ford F-350: http://goapi.curtmfg.com/part/431523?key=9300f7bc-2ca6-11e4-8758-42010af0fd79&brandID=4. 

However, the API doesn't aggregate the F-350 model in the API: http://goapi.curtmfg.com/luverne/vehicle/2017/Ford?key=9300f7bc-2ca6-11e4-8758-42010af0fd79&brandID=4

Must be something wrong with the MongoDB aggregate that's in place. :/

**Comment by dgallegos** [comment]
{"base_vehicle":{"year":"2017","make":"Ford","model":""},"available_models":["E-Series Vans","Expedition","Explorer","F-150","F-250","F-350","Transit"],"lookup_category":null,"products":null}

I see F-350 in "available_models". Should I see something else in "model"?

**Comment by ninnemana** [comment]
I'm sorry, that was an oversight on my part. F-450 is what we're looking for. I'm assuming the error is somewhere in here: https://github.com/curt-labs/API/blob/goapi/models/products/luverne.go#L273-L291

**Comment by dgallegos** [comment]
F-450 and F-550 are the models not showing up.

**Comment by ninnemana** [comment]
Looks good

![image](https://cloud.githubusercontent.com/assets/187030/20812009/977adf3e-b7d5-11e6-8d2d-6e896360fbb3.png)
