### ISSUE TITLE
JC Auto Vehicle Lookup Broken

### ISSUE THREAD

**Issue by dgallegos** [curt-labs/GoAPI#88]
JC Auto, Eau Claire

I received a call from John at JC Auto in Eau Claire. He said Vehicle lookup isn't working on his site, www.hitchesdirect.com. His phone number is 715.215.1310

**Comment by davidvthecoder** [comment]
I believe its a form of this:
https://github.com/curt-labs/CURTeCommerce
and not the Hitch Widget.

I believe this works with v2mock, I will have to confirm.

**Comment by davidvthecoder** [comment]
Update: It is a CURTeCommerce project, It does run off v2.

the domain for the API is a configurable setting in the admin for the site. I called John and requested access. He is currently trying to find the username and password he logs into his site admin with so I can debug further.

He worked closely with Alex on his site and he said he might have to get a hold of Alex to get the credentials.

**Comment by davidvthecoder** [comment]
the API domain was the problem, I found out that on John's website it was using curtapi.curtmfg.com instead of api.curtmfg.com

This commit fixed it:
https://github.com/curt-labs/manifests/pull/25
